# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

ci:
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
      exclude:  ^{{cookiecutter.project_name}}/
    - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: c60c980e561ed3e73101667fe8365c609d19a438 # v0.15.9
    hooks:
    - id: ruff-check
      args: [--fix, --exit-non-zero-on-fix]
      exclude: "^docs|^[{]{2}cookiecutter.project_name[}]{2}/"
    - id: ruff-format
      exclude: "^docs|^[{]{2}cookiecutter.project_name[}]{2}/"
  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: c883505f64b59c3c5c9375191e4ad9f98e727ccd # v1.0.2
    hooks:
    - id: sphinx-lint
      types: [rst]
  - repo: https://github.com/adamchainz/blacken-docs
    rev: fda77690955e9b63c6687d8806bafd56a526e45f # 1.20.0
    hooks:
    - id: blacken-docs
      args: [--line-length=79]
      additional_dependencies:
      - black
  - repo: https://github.com/codespell-project/codespell
    rev: 2ccb47ff45ad361a21071a7eedda4c37e6ae8c5a # v2.4.2
    hooks:
    - id: codespell
