# See https://pyup.io/docs/bot/config/

# configure updates globally
# default: all
# allowed: all, insecure, False
update: all

# configure dependency pinning globally
# default: True
# allowed: True, False
pin: True

# set the default branch
# default: empty, the default branch on GitHub
branch: main

# update schedule
# default: empty
# allowed: "every day", "every week", ..
schedule: "every week"

# search for requirement files
# default: True
# allowed: True, False
search: True

# Specify requirement files by hand, default is empty
# default: empty
# allowed: list
requirements:
  - "constraints_dev.txt":
      # update all dependencies and pin them
      update: all
      pin: True
  - "{{cookiecutter.project_name}}/constraints_dev.txt":
      # update all dependencies and pin them
      update: all
      pin: True

# add a label to pull requests, default is not set
# requires private repo permissions, even on public repos
# default: empty
label_prs: update

# assign users to pull requests, default is not set
# requires private repo permissions, even on public repos
# default: empty
assignees:
 - veit
 - cusyio

# configure the branch prefix the bot is using
# default: pyup-
branch_prefix: pyup/

# set a global prefix for PRs
# default: empty
# pr_prefix:

# allow to close stale PRs
# default: True
close_prs: True
