# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

ci:
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
      exclude:  ^{{cookiecutter.project_name}}/
    - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.3
    hooks:
    - id: ruff-check
      args: [--fix, --exit-non-zero-on-fix]
      exclude: docs
    - id: ruff-format
  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: v1.0.0
    hooks:
    - id: sphinx-lint
      types: [rst]
  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.20.0
    hooks:
    - id: blacken-docs
      args: [--line-length=79]
      additional_dependencies:
      - black
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
    - id: codespell
      files: $(git diff --staged --name-only "*")
{%- endif %}
